variables:
  projectDirectory: 'covid_19_tracker'
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)

